run:
  timeout: 5m

issues:
  exclude-rules:
    - path: \.pb\.go$
      linters:
        - all

linters:
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - gci
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - govet
    - ineffassign
    - misspell
    - unconvert
    - whitespace
  disable:
    - errcheck
    - gosimple
    - nilerr